#pragma config(Sensor, S2,     EyeLeft,        sensorColorNxtFULL)
#pragma config(Sensor, S3,     EyeRight,       sensorLightActive)
#pragma config(Sensor, S4,     sonarsensor,    sensorSONAR)
#pragma config(Motor,  motorA,          right,         tmotorNXT, PIDControl, driveRight, encoder)
#pragma config(Motor,  motorB,          left,          tmotorNXT, PIDControl, driveLeft, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define rightThreshold 45
#define speedlimit 60

int i = 0;

task accelerate();
task deaccelerate();

task deaccelerate ()//geleidelijk stoppen
{
	stopTask(accelerate);
	int k = i;
	for (k = 0; k >= 0; k--)
	{
		wait10Msec(3);
		i = k;
	}
	startTask(accelerate);
}

task accelerate ()//geleidelijk accelereren
{
	stopTask(deaccelerate);
	int k = i;
	for (i = k; i <= speedlimit; i++)
	{
		wait1Msec(30);
	}
	stopTask(accelerate);
}

task remain_stopped()//blijf gestopt totdat obstakel verdwijnt
{
	stopTask(accelerate);
	while(1)
	{
		wait10Msec(5);
		motor[left] = 0;
		motor[right] = 0;
		if (SensorValue(sonarsensor) <! 10)
			break;
	}
	stopTask(remain_stopped);
	startTask(accelerate);
}

task main()
{
	startTask(accelerate);
	while(1)
	{
		while (SensorValue(sonarsensor) > 5)
		{
			while (SensorValue(sonarsensor) > 25)
			{
				if ((SensorValue(EyeLeft) == BLACKCOLOR) && (SensorValue(EyeRight) <= rightThreshold))
    		{
      	  	//
      	  	// Beide sensoren zien lijn, oftewel kruispunt.
      	  	//
    				motor[left] = 0;
    				motor[right] = 0;
   	 		}

    		if ((SensorValue(EyeLeft) == BLACKCOLOR)&&(SensorValue(EyeRight)> rightThreshold))
    		{
        		//
        		// Only left sensor sees the line, we must turn left.
        		//
        		motor[left] = i;
        		motor[right] = i/6;
    		}

    		if ((SensorValue(EyeLeft) == WHITECOLOR) &&(SensorValue(EyeRight)< rightThreshold))
    		{
       	 		//
       	 		// Only right sensor sees the line, turn right.
        		//
        		motor[left] = i/6;
        		motor[right] = i;
    		}

				if ((SensorValue(EyeLeft) == WHITECOLOR)&&(SensorValue(EyeRight) > rightThreshold))
				{
					motor[left] = i/2;
      		motor[right] = i/2;
    		}
   		}
   		startTask(deaccelerate);
		}
		startTask(remain_stopped);
	}
}
